# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "node-shopi"
client_id = "912396a2b89d91924e0ed5a419973c42"
application_url = "https://dress-tracking-bowling-atomic.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://dress-tracking-bowling-atomic.trycloudflare.com/auth/callback",
  "https://dress-tracking-bowling-atomic.trycloudflare.com/auth/shopify/callback",
  "https://dress-tracking-bowling-atomic.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "falconbuu.myshopify.com"
